/**
 * صلاحيات Noorix — نظام صلاحيات قائم على الأقسام.
 * الأدوار المخصصة تحمل صلاحياتها في قاعدة البيانات.
 */

export const PERMISSIONS = {
  VIEW_OWNER:       'VIEW_OWNER',
  VIEW_DASHBOARD:   'VIEW_DASHBOARD',
  VIEW_CHAT:        'VIEW_CHAT',
  VIEW_SALES:       'VIEW_SALES',
  VIEW_INVOICES:    'VIEW_INVOICES',
  VIEW_SUPPLIERS:   'VIEW_SUPPLIERS',
  VIEW_VAULTS:      'VIEW_VAULTS',
  VIEW_REPORTS:     'VIEW_REPORTS',
  VIEW_EMPLOYEES:   'VIEW_EMPLOYEES',
  VIEW_ORDERS:      'VIEW_ORDERS',
  VIEW_EXPENSES:    'VIEW_EXPENSES',

  INVOICES_READ:    'INVOICES_READ',
  INVOICES_WRITE:   'INVOICES_WRITE',
  INVOICES_DELETE:  'INVOICES_DELETE',
  INVOICES_ACTIONS: 'INVOICES_ACTIONS',

  SALES_READ:       'SALES_READ',
  SALES_WRITE:      'SALES_WRITE',
  SALES_DELETE:     'SALES_DELETE',
  SALES_ACTIONS:    'SALES_ACTIONS',

  SUPPLIERS_READ:   'SUPPLIERS_READ',
  SUPPLIERS_WRITE:  'SUPPLIERS_WRITE',
  SUPPLIERS_DELETE: 'SUPPLIERS_DELETE',

  VAULTS_READ:      'VAULTS_READ',
  VAULTS_WRITE:     'VAULTS_WRITE',
  VAULTS_DELETE:    'VAULTS_DELETE',

  EXPENSES_READ:    'EXPENSES_READ',
  EXPENSES_WRITE:   'EXPENSES_WRITE',
  EXPENSES_DELETE:  'EXPENSES_DELETE',

  ORDERS_READ:      'ORDERS_READ',
  ORDERS_WRITE:     'ORDERS_WRITE',
  ORDERS_DELETE:    'ORDERS_DELETE',

  REPORTS_READ:     'REPORTS_READ',

  SMART_CHAT_READ:  'SMART_CHAT_READ',

  /** اختصارات المحادثة الذكية — تُعرض في الواجهة وتُدار من مصفوفة الأدوار */
  CHAT_PRESET_ADVANCES:  'CHAT_PRESET_ADVANCES',
  CHAT_PRESET_LEAVES:    'CHAT_PRESET_LEAVES',
  CHAT_PRESET_DEDUCTIONS:'CHAT_PRESET_DEDUCTIONS',
  CHAT_PRESET_FAQ:       'CHAT_PRESET_FAQ',

  EMPLOYEES_READ:   'EMPLOYEES_READ',
  EMPLOYEES_WRITE:  'EMPLOYEES_WRITE',
  EMPLOYEES_DELETE: 'EMPLOYEES_DELETE',

  HR_READ:          'HR_READ',
  HR_WRITE:         'HR_WRITE',
  HR_DELETE:        'HR_DELETE',

  MANAGE_SETTINGS:  'MANAGE_SETTINGS',
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  MANAGE_USERS:     'MANAGE_USERS',

  DELETE_COMPANY:   'DELETE_COMPANY',
  USERS_DELETE:     'USERS_DELETE',

  CREATE_INVOICE:   'CREATE_INVOICE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  OWNER:       'owner',
  ACCOUNTANT:  'accountant',
  CASHIER:     'cashier',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.OWNER]:       ALL,
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CHAT,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.VIEW_VAULTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_EXPENSES,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.INVOICES_ACTIONS,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_WRITE,
    PERMISSIONS.SALES_ACTIONS,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.VAULTS_READ,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.EXPENSES_WRITE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.EMPLOYEES_WRITE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_WRITE,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.SMART_CHAT_READ,
    PERMISSIONS.CHAT_PRESET_ADVANCES,
    PERMISSIONS.CHAT_PRESET_LEAVES,
    PERMISSIONS.CHAT_PRESET_DEDUCTIONS,
    PERMISSIONS.CHAT_PRESET_FAQ,
    PERMISSIONS.CREATE_INVOICE,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.VIEW_CHAT,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.VIEW_VAULTS,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_WRITE,
    PERMISSIONS.SALES_ACTIONS,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.INVOICES_ACTIONS,
    PERMISSIONS.VAULTS_READ,
    PERMISSIONS.SMART_CHAT_READ,
    PERMISSIONS.CHAT_PRESET_FAQ,
    PERMISSIONS.CREATE_INVOICE,
  ],
};

/**
 * hasPermission — يدعم الفحص من الدور الثابت أو من مصفوفة صلاحيات (DB).
 * يُستخدم في RolesGuard مع الصلاحيات المحملة في JWT.
 */
export function hasPermission(role: string, permission: Permission, userPermissions?: string[]): boolean {
  const r = (role || '').toLowerCase();
  if (r === ROLES.SUPER_ADMIN || r === ROLES.OWNER) return true;

  if (Array.isArray(userPermissions) && userPermissions.length > 0) {
    return userPermissions.includes(permission);
  }

  const perms = ROLE_PERMISSIONS[r];
  return Array.isArray(perms) && perms.includes(permission);
}

export function isSuperAdmin(role: string): boolean {
  const r = (role || '').toLowerCase();
  return r === ROLES.SUPER_ADMIN || r === ROLES.OWNER;
}
