/**
 * Presets لمصفوفة الأدوار — مرآة لبذور الأدوار النظامية + «محاسب بدون خزائن».
 */
import { PERMISSIONS } from '../../../constants/permissions';

const CHAT_FAQ_ALL = [
  PERMISSIONS.CHAT_FAQ_ANNUAL_SALES,
  PERMISSIONS.CHAT_FAQ_VAULT_BALANCES,
  PERMISSIONS.CHAT_FAQ_PNL_SUMMARY,
  PERMISSIONS.CHAT_FAQ_LOAD_VS_SALES,
  PERMISSIONS.CHAT_FAQ_SALES_COMPARE,
  PERMISSIONS.CHAT_FAQ_INVOICE_COUNT,
  PERMISSIONS.CHAT_FAQ_SUPPLIER_COUNT,
  PERMISSIONS.CHAT_FAQ_EMPLOYEE_COUNT,
  PERMISSIONS.CHAT_FAQ_HELP,
] as const;

const ACCOUNTANT_PERMISSIONS: string[] = [
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.VIEW_INVOICES,
  PERMISSIONS.VIEW_SUPPLIERS,
  PERMISSIONS.VIEW_VAULTS,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_SALES,
  PERMISSIONS.VIEW_EMPLOYEES,
  PERMISSIONS.VIEW_ORDERS,
  PERMISSIONS.VIEW_EXPENSES,
  PERMISSIONS.VIEW_ASSETS,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.INVOICES_WRITE,
  PERMISSIONS.INVOICES_ACTIONS,
  PERMISSIONS.INVOICES_VIEW_EXEC_SUMMARY,
  PERMISSIONS.VIEW_PURCHASES,
  PERMISSIONS.PURCHASES_READ,
  PERMISSIONS.PURCHASES_WRITE,
  PERMISSIONS.PURCHASES_DELETE,
  PERMISSIONS.SALES_READ,
  PERMISSIONS.SALES_WRITE,
  PERMISSIONS.SALES_ACTIONS,
  PERMISSIONS.SALES_FULL_HISTORY,
  PERMISSIONS.SALES_VIEW_SUMMARIES_LIST,
  PERMISSIONS.SUPPLIERS_READ,
  PERMISSIONS.VAULTS_READ,
  PERMISSIONS.EXPENSES_READ,
  PERMISSIONS.EXPENSES_WRITE,
  PERMISSIONS.ASSETS_READ,
  PERMISSIONS.ASSETS_WRITE,
  PERMISSIONS.ORDERS_READ,
  PERMISSIONS.ORDERS_WRITE,
  PERMISSIONS.REPORTS_READ,
  PERMISSIONS.VIEW_REPORTS_GENERAL,
  PERMISSIONS.VIEW_REPORTS_COST_APPS,
  PERMISSIONS.VIEW_REPORTS_TAX,
  PERMISSIONS.VIEW_REPORTS_BANK,
  PERMISSIONS.VIEW_HAJRI_TAX,
  PERMISSIONS.HAJRI_TAX_READ,
  PERMISSIONS.HAJRI_TAX_WRITE,
  PERMISSIONS.EMPLOYEES_READ,
  PERMISSIONS.EMPLOYEES_WRITE,
  PERMISSIONS.VIEW_HR,
  PERMISSIONS.HR_READ,
  PERMISSIONS.HR_WRITE,
  PERMISSIONS.HR_DELETE,
  PERMISSIONS.HR_LEAVE_SALARY_OVERRIDE,
  PERMISSIONS.SMART_CHAT_READ,
  PERMISSIONS.CHAT_PRESET_ADVANCES,
  PERMISSIONS.CHAT_PRESET_LEAVES,
  PERMISSIONS.CHAT_PRESET_DEDUCTIONS,
  PERMISSIONS.CHAT_PRESET_INCREASES,
  PERMISSIONS.CHAT_PRESET_ADD_EMPLOYEE,
  PERMISSIONS.CHAT_PRESET_EXPENSE_ADD,
  PERMISSIONS.CHAT_PRESET_EXPENSE_PAY,
  PERMISSIONS.CHAT_PRESET_EXPENSE_EDIT,
  ...CHAT_FAQ_ALL,
  PERMISSIONS.CREATE_INVOICE,
];

const VAULT_RELATED = new Set<string>([
  PERMISSIONS.VIEW_VAULTS,
  PERMISSIONS.VAULTS_READ,
  PERMISSIONS.VAULTS_WRITE,
  PERMISSIONS.VAULTS_DELETE,
  PERMISSIONS.CHAT_FAQ_VAULT_BALANCES,
]);

const CASHIER_PERMISSIONS: string[] = [
  PERMISSIONS.VIEW_CHAT,
  PERMISSIONS.VIEW_SALES,
  PERMISSIONS.VIEW_INVOICES,
  PERMISSIONS.VIEW_ORDERS,
  PERMISSIONS.STAFF_ORDERS_SUBMIT,
  PERMISSIONS.SALES_READ,
  PERMISSIONS.SALES_WRITE,
  PERMISSIONS.SALES_ACTIONS,
  PERMISSIONS.SALES_FULL_HISTORY,
  PERMISSIONS.SALES_VIEW_SUMMARIES_LIST,
  PERMISSIONS.INVOICES_READ,
  PERMISSIONS.INVOICES_WRITE,
  PERMISSIONS.INVOICES_ACTIONS,
  PERMISSIONS.VIEW_PURCHASES,
  PERMISSIONS.PURCHASES_READ,
  PERMISSIONS.SMART_CHAT_READ,
  PERMISSIONS.CHAT_FAQ_ANNUAL_SALES,
  PERMISSIONS.CHAT_FAQ_SALES_COMPARE,
  PERMISSIONS.CHAT_FAQ_INVOICE_COUNT,
  PERMISSIONS.CHAT_FAQ_HELP,
  PERMISSIONS.CREATE_INVOICE,
];

export type RolePreset = {
  id: string;
  labelAr: string;
  labelEn: string;
  permissions: string[];
};

export const ROLE_PRESETS: RolePreset[] = [
  {
    id: 'accountant',
    labelAr: 'محاسب (كامل)',
    labelEn: 'Accountant (full)',
    permissions: ACCOUNTANT_PERMISSIONS,
  },
  {
    id: 'accountant_no_vaults',
    labelAr: 'محاسب بدون خزائن',
    labelEn: 'Accountant (no vaults)',
    permissions: ACCOUNTANT_PERMISSIONS.filter((p) => !VAULT_RELATED.has(p)),
  },
  {
    id: 'cashier',
    labelAr: 'كاشير',
    labelEn: 'Cashier',
    permissions: CASHIER_PERMISSIONS,
  },
];
