import {
  TAX_RATE,
  add,
  addTax,
  div,
  mul,
  normalizeDecimal,
  resolveVatRateDecimal,
  roundAmount,
  roundAmountAsNumber,
  splitTax,
  splitTaxBalancedHalalas,
  splitTaxFromTotal,
  splitTaxFromTotalAsNumbers,
  sub,
  sumAmounts,
  sumObjectValues,
  taxAmount,
  toHalalas,
} from '@noorix/finance-core';

export {
  TAX_RATE,
  add,
  addTax,
  div,
  mul,
  normalizeDecimal,
  resolveVatRateDecimal,
  roundAmount,
  roundAmountAsNumber,
  splitTax,
  splitTaxBalancedHalalas,
  splitTaxFromTotal,
  splitTaxFromTotalAsNumbers,
  sub,
  sumAmounts,
  sumObjectValues,
  taxAmount,
  toHalalas,
};
