import { normalizeDirectoryText } from './supplier-directory-search.util';

export type SupplierDirectoryEntityType =
  | 'government'
  | 'government_platform'
  | 'utility'
  | 'telecom';

export type SupplierDirectorySeed = {
  code: string;
  nameAr: string;
  nameEn: string;
  aliases: string[];
  entityType: SupplierDirectoryEntityType;
  defaultCategoryCode: string;
  isTaxRegistered: boolean;
  supplierInvoiceNumberRequired: boolean;
  sortOrder: number;
};

const rows: SupplierDirectorySeed[] = [
  {
    code: 'GOV-GOSI',
    nameAr: 'المؤسسة العامة للتأمينات الاجتماعية',
    nameEn: 'General Organization for Social Insurance (GOSI)',
    aliases: ['GOSI', 'التأمينات', 'التأمينات الاجتماعية'],
    entityType: 'government',
    defaultCategoryCode: 'E2-8',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 10,
  },
  {
    code: 'GOV-ZATCA',
    nameAr: 'هيئة الزكاة والضريبة والجمارك',
    nameEn: 'Zakat, Tax and Customs Authority (ZATCA)',
    aliases: ['هيئة الزكاة والدخل', 'الزكاة والدخل', 'ZATCA', 'VAT GOV'],
    entityType: 'government',
    defaultCategoryCode: 'E2-7',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 20,
  },
  {
    code: 'GOV-MOC',
    nameAr: 'وزارة التجارة',
    nameEn: 'Ministry of Commerce',
    aliases: ['التجارة', 'MOC'],
    entityType: 'government',
    defaultCategoryCode: 'E2-1',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 30,
  },
  {
    code: 'GOV-SBC',
    nameAr: 'المركز السعودي للأعمال الاقتصادية',
    nameEn: 'Saudi Business Center',
    aliases: ['المركز السعودي للأعمال', 'منصة الأعمال', 'SBC'],
    entityType: 'government',
    defaultCategoryCode: 'E2-1',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 40,
  },
  {
    code: 'GOV-MOMAH',
    nameAr: 'وزارة البلديات والإسكان',
    nameEn: 'Ministry of Municipalities and Housing',
    aliases: ['وزارة الشؤون البلدية والقروية والإسكان', 'وزارة البلدية', 'البلدية', 'MOMAH'],
    entityType: 'government',
    defaultCategoryCode: 'E2-2',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 50,
  },
  {
    code: 'GOV-HRSD',
    nameAr: 'وزارة الموارد البشرية والتنمية الاجتماعية',
    nameEn: 'Ministry of Human Resources and Social Development',
    aliases: ['وزارة العمل', 'الموارد البشرية', 'HRSD'],
    entityType: 'government',
    defaultCategoryCode: 'E2-10',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 60,
  },
  {
    code: 'GOV-PASSPORTS',
    nameAr: 'المديرية العامة للجوازات',
    nameEn: 'General Directorate of Passports',
    aliases: ['الجوازات', 'وزارة الداخلية الجوازات', 'Passports'],
    entityType: 'government',
    defaultCategoryCode: 'E2-4',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 70,
  },
  {
    code: 'GOV-CIVIL-DEFENSE',
    nameAr: 'المديرية العامة للدفاع المدني',
    nameEn: 'General Directorate of Civil Defense',
    aliases: ['الدفاع المدني', 'سلامة', 'Civil Defense'],
    entityType: 'government',
    defaultCategoryCode: 'E2-3',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 80,
  },
  {
    code: 'GOV-MOJ',
    nameAr: 'وزارة العدل',
    nameEn: 'Ministry of Justice',
    aliases: ['العدل', 'MOJ'],
    entityType: 'government',
    defaultCategoryCode: 'E2-7',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 90,
  },
  {
    code: 'GOV-MISA',
    nameAr: 'وزارة الاستثمار',
    nameEn: 'Ministry of Investment',
    aliases: ['الاستثمار', 'MISA', 'SAGIA'],
    entityType: 'government',
    defaultCategoryCode: 'E2-1',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 100,
  },
  {
    code: 'GOV-SFDA',
    nameAr: 'الهيئة العامة للغذاء والدواء',
    nameEn: 'Saudi Food and Drug Authority (SFDA)',
    aliases: ['الغذاء والدواء', 'SFDA'],
    entityType: 'government',
    defaultCategoryCode: 'E2-7',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 110,
  },
  {
    code: 'GOV-SASO',
    nameAr: 'الهيئة السعودية للمواصفات والمقاييس والجودة',
    nameEn: 'Saudi Standards, Metrology and Quality Organization (SASO)',
    aliases: ['هيئة المواصفات', 'المواصفات والمقاييس', 'SASO'],
    entityType: 'government',
    defaultCategoryCode: 'E2-7',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 120,
  },
  {
    code: 'GOV-SAIP',
    nameAr: 'الهيئة السعودية للملكية الفكرية',
    nameEn: 'Saudi Authority for Intellectual Property (SAIP)',
    aliases: ['الملكية الفكرية', 'SAIP'],
    entityType: 'government',
    defaultCategoryCode: 'E2-7',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 130,
  },
  {
    code: 'GOV-FSC',
    nameAr: 'اتحاد الغرف السعودية',
    nameEn: 'Federation of Saudi Chambers',
    aliases: ['مجلس الغرف السعودية', 'الغرفة التجارية', 'اتحاد الغرف', 'FSC'],
    entityType: 'government',
    defaultCategoryCode: 'E2-1',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 140,
  },
  {
    code: 'PLT-QIWA',
    nameAr: 'منصة قوى',
    nameEn: 'Qiwa Platform',
    aliases: ['قوى', 'QIWA'],
    entityType: 'government_platform',
    defaultCategoryCode: 'E2-10',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 200,
  },
  {
    code: 'PLT-MUDAD',
    nameAr: 'منصة مدد',
    nameEn: 'Mudad Platform',
    aliases: ['مدد', 'MUDAD'],
    entityType: 'government_platform',
    defaultCategoryCode: 'E2-10',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 210,
  },
  {
    code: 'PLT-MUQEEM',
    nameAr: 'منصة مقيم',
    nameEn: 'Muqeem Platform',
    aliases: ['مقيم', 'MUQEEM'],
    entityType: 'government_platform',
    defaultCategoryCode: 'E2-10',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 220,
  },
  {
    code: 'PLT-BALADY',
    nameAr: 'منصة بلدي',
    nameEn: 'Balady Platform',
    aliases: ['بلدي', 'BALADY'],
    entityType: 'government_platform',
    defaultCategoryCode: 'E2-10',
    isTaxRegistered: false,
    supplierInvoiceNumberRequired: false,
    sortOrder: 230,
  },
  {
    code: 'UTL-SA-ENERGY',
    nameAr: 'السعودية للطاقة',
    nameEn: 'Saudi Energy',
    aliases: ['الشركة السعودية للكهرباء', 'السعودية للكهرباء', 'Saudi Electricity Company', 'SEC'],
    entityType: 'utility',
    defaultCategoryCode: 'E3-2',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 300,
  },
  {
    code: 'UTL-NWC',
    nameAr: 'شركة المياه الوطنية',
    nameEn: 'National Water Company (NWC)',
    aliases: ['المياه الوطنية', 'NWC'],
    entityType: 'utility',
    defaultCategoryCode: 'E3-4',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 310,
  },
  {
    code: 'TEL-STC',
    nameAr: 'شركة الاتصالات السعودية (stc)',
    nameEn: 'Saudi Telecom Company (stc)',
    aliases: ['الاتصالات السعودية', 'STC', 'Saudi Telecom Company'],
    entityType: 'telecom',
    defaultCategoryCode: 'E3-3',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 400,
  },
  {
    code: 'TEL-MOBILY',
    nameAr: 'شركة اتحاد اتصالات (Mobily)',
    nameEn: 'Etihad Etisalat Company (Mobily)',
    aliases: ['موبايلي', 'Mobily', 'اتحاد اتصالات'],
    entityType: 'telecom',
    defaultCategoryCode: 'E3-3',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 410,
  },
  {
    code: 'TEL-ZAIN',
    nameAr: 'شركة الاتصالات المتنقلة السعودية (Zain)',
    nameEn: 'Mobile Telecommunication Company Saudi Arabia (Zain)',
    aliases: ['زين', 'Zain', 'زين السعودية'],
    entityType: 'telecom',
    defaultCategoryCode: 'E3-3',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 420,
  },
  {
    code: 'TEL-SALAM',
    nameAr: 'شركة الاتصالات المتكاملة (Salam)',
    nameEn: 'Integrated Telecom Company (Salam)',
    aliases: ['سلام', 'Salam', 'سلام موبايل', 'ITC'],
    entityType: 'telecom',
    defaultCategoryCode: 'E3-3',
    isTaxRegistered: true,
    supplierInvoiceNumberRequired: true,
    sortOrder: 430,
  },
];

export const SUPPLIER_DIRECTORY_SEEDS = rows.map((row) => ({
  ...row,
  searchText: normalizeDirectoryText([row.nameAr, row.nameEn, ...row.aliases].join(' ')),
}));

export const SUPPLIER_DIRECTORY_CODES = new Set(
  SUPPLIER_DIRECTORY_SEEDS.map((row) => row.code),
);
