export const PERMISSIONS = {
  VIEW_OWNER: 'VIEW_OWNER',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_CHAT: 'VIEW_CHAT',
  VIEW_SALES: 'VIEW_SALES',
  VIEW_INVOICES: 'VIEW_INVOICES',
  VIEW_PURCHASES: 'VIEW_PURCHASES',
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  VIEW_VAULTS: 'VIEW_VAULTS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  VIEW_ORDERS: 'VIEW_ORDERS',
  VIEW_INTERNAL_REGISTRATION: 'VIEW_INTERNAL_REGISTRATION',
  VIEW_EXPENSES: 'VIEW_EXPENSES',
  VIEW_ASSETS: 'VIEW_ASSETS',

  INVOICES_READ: 'INVOICES_READ',
  INVOICES_WRITE: 'INVOICES_WRITE',
  INVOICES_DELETE: 'INVOICES_DELETE',
  INVOICES_ACTIONS: 'INVOICES_ACTIONS',
  INVOICES_VIEW_EXEC_SUMMARY: 'INVOICES_VIEW_EXEC_SUMMARY',

  PURCHASES_READ: 'PURCHASES_READ',
  PURCHASES_WRITE: 'PURCHASES_WRITE',
  PURCHASES_DELETE: 'PURCHASES_DELETE',

  SALES_READ: 'SALES_READ',
  SALES_WRITE: 'SALES_WRITE',
  SALES_DELETE: 'SALES_DELETE',
  SALES_ACTIONS: 'SALES_ACTIONS',
  SALES_FULL_HISTORY: 'SALES_FULL_HISTORY',
  SALES_VIEW_SUMMARIES_LIST: 'SALES_VIEW_SUMMARIES_LIST',

  SUPPLIERS_READ: 'SUPPLIERS_READ',
  SUPPLIERS_WRITE: 'SUPPLIERS_WRITE',
  SUPPLIERS_DELETE: 'SUPPLIERS_DELETE',

  VAULTS_READ: 'VAULTS_READ',
  VAULTS_WRITE: 'VAULTS_WRITE',
  VAULTS_DELETE: 'VAULTS_DELETE',

  EXPENSES_READ: 'EXPENSES_READ',
  EXPENSES_WRITE: 'EXPENSES_WRITE',
  EXPENSES_DELETE: 'EXPENSES_DELETE',

  ASSETS_READ: 'ASSETS_READ',
  ASSETS_WRITE: 'ASSETS_WRITE',
  ASSETS_DELETE: 'ASSETS_DELETE',

  ORDERS_READ: 'ORDERS_READ',
  ORDERS_WRITE: 'ORDERS_WRITE',
  ORDERS_DELETE: 'ORDERS_DELETE',

  REPORTS_READ: 'REPORTS_READ',
  VIEW_REPORTS_GENERAL: 'VIEW_REPORTS_GENERAL',
  VIEW_REPORTS_COST_APPS: 'VIEW_REPORTS_COST_APPS',
  VIEW_REPORTS_TAX: 'VIEW_REPORTS_TAX',
  VIEW_REPORTS_BANK: 'VIEW_REPORTS_BANK',

  VIEW_HAJRI_TAX: 'VIEW_HAJRI_TAX',
  HAJRI_TAX_READ: 'HAJRI_TAX_READ',
  HAJRI_TAX_WRITE: 'HAJRI_TAX_WRITE',

  VIEW_HR: 'VIEW_HR',

  SMART_CHAT_READ: 'SMART_CHAT_READ',

  CHAT_PRESET_ADVANCES: 'CHAT_PRESET_ADVANCES',
  CHAT_PRESET_LEAVES: 'CHAT_PRESET_LEAVES',
  CHAT_PRESET_DEDUCTIONS: 'CHAT_PRESET_DEDUCTIONS',
  CHAT_PRESET_FAQ: 'CHAT_PRESET_FAQ',
  CHAT_PRESET_INCREASES: 'CHAT_PRESET_INCREASES',
  CHAT_PRESET_ADD_EMPLOYEE: 'CHAT_PRESET_ADD_EMPLOYEE',
  CHAT_PRESET_EXPENSE_ADD: 'CHAT_PRESET_EXPENSE_ADD',
  CHAT_PRESET_EXPENSE_PAY: 'CHAT_PRESET_EXPENSE_PAY',
  CHAT_PRESET_EXPENSE_EDIT: 'CHAT_PRESET_EXPENSE_EDIT',

  CHAT_FAQ_ANNUAL_SALES: 'CHAT_FAQ_ANNUAL_SALES',
  CHAT_FAQ_VAULT_BALANCES: 'CHAT_FAQ_VAULT_BALANCES',
  CHAT_FAQ_PNL_SUMMARY: 'CHAT_FAQ_PNL_SUMMARY',
  CHAT_FAQ_LOAD_VS_SALES: 'CHAT_FAQ_LOAD_VS_SALES',
  CHAT_FAQ_SALES_COMPARE: 'CHAT_FAQ_SALES_COMPARE',
  CHAT_FAQ_INVOICE_COUNT: 'CHAT_FAQ_INVOICE_COUNT',
  CHAT_FAQ_SUPPLIER_COUNT: 'CHAT_FAQ_SUPPLIER_COUNT',
  CHAT_FAQ_EMPLOYEE_COUNT: 'CHAT_FAQ_EMPLOYEE_COUNT',
  CHAT_FAQ_HELP: 'CHAT_FAQ_HELP',

  EMPLOYEES_READ: 'EMPLOYEES_READ',
  EMPLOYEES_WRITE: 'EMPLOYEES_WRITE',
  EMPLOYEES_DELETE: 'EMPLOYEES_DELETE',

  HR_READ: 'HR_READ',
  HR_WRITE: 'HR_WRITE',
  HR_DELETE: 'HR_DELETE',
  HR_LEAVE_SALARY_OVERRIDE: 'HR_LEAVE_SALARY_OVERRIDE',

  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  MANAGE_TAX_SETTINGS: 'MANAGE_TAX_SETTINGS',
  MANAGE_USERS: 'MANAGE_USERS',

  DELETE_COMPANY: 'DELETE_COMPANY',
  USERS_DELETE: 'USERS_DELETE',

  CREATE_INVOICE: 'CREATE_INVOICE',

  STAFF_ORDERS_READ: 'STAFF_ORDERS_READ',
  STAFF_ORDERS_SUBMIT: 'STAFF_ORDERS_SUBMIT',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const CHAT_FAQ_PERMISSIONS: Permission[] = [
  PERMISSIONS.CHAT_FAQ_ANNUAL_SALES,
  PERMISSIONS.CHAT_FAQ_VAULT_BALANCES,
  PERMISSIONS.CHAT_FAQ_PNL_SUMMARY,
  PERMISSIONS.CHAT_FAQ_LOAD_VS_SALES,
  PERMISSIONS.CHAT_FAQ_SALES_COMPARE,
  PERMISSIONS.CHAT_FAQ_INVOICE_COUNT,
  PERMISSIONS.CHAT_FAQ_SUPPLIER_COUNT,
  PERMISSIONS.CHAT_FAQ_EMPLOYEE_COUNT,
  PERMISSIONS.CHAT_FAQ_HELP,
];

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  OWNER: 'owner',
  ACCOUNTANT: 'accountant',
  CASHIER: 'cashier',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];
